# -*- coding: utf-8 -*-
"""Convert first-person voice to objective/passive in main_journal.tex."""
import io
F = 'main_journal.tex'
s = io.open(F, encoding='utf-8').read()

R = [
 ("We group the related work into four areas",
  "The related work is grouped into four areas"),
 ("which is closer to our own task.", "which is closer to the present task."),
 ("and it is precisely why we invested most",
  "and it is precisely why most effort"),
 ("of our effort in the 150-feature matrix and treated the model comparison as a",
  "went into the 150-feature matrix, with the model comparison treated as a"),
 ("shaped how we allocated our time.", "shaped the allocation of effort."),
 ("because the shape of our target", "because the shape of the target"),
 ("affine functions}. Our target, however, is a",
  "affine functions}. The target, however, is a"),
 ("Our target is a bounded count with a large spike at zero, and the statistics",
  "The target is a bounded count with a large spike at zero, and the statistics"),
 ("generative mechanism. We did not adopt these parametric estimators in the final",
  "generative mechanism. These parametric estimators are not adopted in the final"),
 ("we propose in Section~\\ref{sec:concl}. The residual analysis in",
  "proposed in Section~\\ref{sec:concl}. The residual analysis in"),
 ("unified statistical picture behind all of these, and we used scikit-learn",
  "unified statistical picture behind all of these, and scikit-learn"),
 ("\\cite{pedregosa2011sklearn} as the common Python interface throughout.",
  "\\cite{pedregosa2011sklearn} is used as the common Python interface throughout."),
 ("score, which is usually the case. We followed that advice but, as",
  "score, which is usually the case. This advice is followed; however, as"),
 ("Section~\\ref{sec:changes} explains, we ended up writing our own randomized",
  "Section~\\ref{sec:changes} explains, a custom randomized"),
 ("specifically so that we could combine the search with fold-level early stopping.",
  "specifically to combine the search with fold-level early stopping."),
 ("lowers the variance of the performance estimate and stops us from tuning to a",
  "lowers the variance of the performance estimate and prevents tuning to a"),
 ("recommends paired resampling tests, which we",
  "recommends paired resampling tests, which are"),
 ("adopt in Section~\\ref{sec:significance}.",
  "adopted in Section~\\ref{sec:significance}."),
 ("property $i$, we want a function $f$ such that",
  "property $i$, the goal is a function $f$ such that"),
 ("actual notebooks in our repository: exploratory analysis, feature engineering,",
  "actual processing stages: exploratory analysis, feature engineering,"),
 ("observations changed our later decisions. First, the target is heavily skewed",
  "observations shaped later decisions. First, the target is heavily skewed"),
 ("not just noise. Third, when we computed simple per-property aggregates from the",
  "not just noise. Third, when simple per-property aggregates were computed from the"),
 ("That told us early on that the daily files, not",
  "That indicated early that the daily files, not"),
 ("typically marks an inactive host), we encode missingness explicitly with",
  "typically marks an inactive host), missingness is encoded explicitly with"),
 ("matrix with one row per \\texttt{PropertyID}. We ended up with 150 features (144",
  "matrix with one row per \\texttt{PropertyID}. The result is 150 features (144"),
 ("property we counted the days available, booked, and reserved, the number of",
  "property, the days available, booked, and reserved are counted, with the number of"),
 ("number of distinct prices). From these we derived",
  "number of distinct prices). From these are derived"),
 ("differently from the rest of the week, so we split each quarter into weekend and",
  "differently from the rest of the week, so each quarter is split into weekend and"),
 ("From the listing title we extracted simple binary\nflags for the presence of words like",
  "Binary flags are extracted from the listing\ntitle for the presence of words like"),
 ("\\item \\textbf{Geographic clusters.} We ran K-Means ($k=12$) on",
  "\\item \\textbf{Geographic clusters.} K-Means ($k=12$) is run on"),
 ("feature-importance ranking we report later (Fig.~\\ref{fig:importance}).",
  "feature-importance ranking reported later (Fig.~\\ref{fig:importance})."),
 ("median-imputed (robust to the outliers we saw in price) with missing-indicator",
  "median-imputed (robust to the price outliers) with missing-indicator"),
 ("test rows) we use the full-data map.", "test rows), the full-data map is used."),
 ("estimates into the model. For XGBoost we additionally lean on its",
  "estimates into the model. For XGBoost, the model additionally relies on its"),
 ("For the linear\nbaseline we apply \\texttt{StandardScaler}; for the tree models scaling is\nunnecessary, but we keep the rest of the pipeline identical so the comparison is",
  "For the linear\nbaseline, \\texttt{StandardScaler} is applied; for the tree models scaling is\nunnecessary, but the rest of the pipeline is kept identical so the comparison is"),
 ("A plain linear regression gives us an interpretable lower bar and tells us which",
  "A plain linear regression provides an interpretable lower bound and indicates which"),
 ("needs little tuning. We use it as a strong non-linear reference point.",
  "needs little tuning. It serves as a strong non-linear reference point."),
 ("penalties. We tuned these most aggressively",
  "penalties. These are tuned most aggressively"),
 ("Finally, we trained a small feed-forward neural network in PyTorch",
  "Finally, a small feed-forward neural network is trained in PyTorch"),
 ("\\cite{tang2024,camatti2024} led us to expect the trees to win, and they",
  "\\cite{tang2024,camatti2024} suggested the trees would win, and they"),
 ("predictions to the count scale. This is not a contradiction with our decision to",
  "predictions to the count scale. This does not contradict the decision to"),
 ("For XGBoost we wrote our own randomized search instead of using",
  "For XGBoost, a custom randomized search is used instead of"),
 ("\\texttt{RandomizedSearchCV}, because we wanted fold-level early stopping: inside",
  "\\texttt{RandomizedSearchCV}, to enable fold-level early stopping: inside"),
 ("each of the five outer folds we carve out a small internal validation set, fit",
  "each of the five outer folds, a small internal validation set is carved out, fitting"),
 ("\\texttt{RandomizedSearchCV} does not let us pass a",
  "\\texttt{RandomizedSearchCV} does not cleanly allow a"),
 ("option, and it also let us log every configuration we tried.",
  "option, and it also logs every configuration tried."),
 ("within fold $k$ we split the training part",
  "within fold $k$ the training part is split"),
 ("We draw $N=60$ configurations from the product of the marginals in",
  "A total of $N=60$ configurations are drawn from the product of the marginals in"),
 ("Our best configuration (Table~\\ref{tab:xgbparams}) used a learning rate of",
  "The best configuration (Table~\\ref{tab:xgbparams}) uses a learning rate of"),
 ("\\noindent\\emph{Note.} In our primary implementation",
  "\\noindent\\emph{Note.} In the primary implementation"),
 ("(\\texttt{05\\_Gradient\\_Boosting\\_XGBoost.ipynb}) we used a 1{,}000-estimator cap",
  "(\\texttt{05\\_Gradient\\_Boosting\\_XGBoost.ipynb}), a 1{,}000-estimator cap is used"),
 ("Rather than submit a single model, we combine the out-of-fold (OOF) predictions",
  "Rather than using a single model, the out-of-fold (OOF) predictions are combined"),
 ("$j$ holding model $j$'s OOF prediction. We seek weights",
  "$j$ holding model $j$'s OOF prediction. The aim is to find weights"),
 ("from receiving a runaway weight. We solve \\eqref{eq:blendobj}--\\eqref{eq:blendbox}",
  "from receiving a runaway weight. Problem \\eqref{eq:blendobj}--\\eqref{eq:blendbox} is solved"),
 ("\\texttt{ftol}~$=10^{-9}$. As a post-processing step we zero\nout negligible weights ($w_j<10^{-4}$) and renormalize so that",
  "\\texttt{ftol}~$=10^{-9}$. As a post-processing step, weights below $10^{-4}$\nare zeroed and the rest renormalized so that"),
 ("\\eqref{eq:blendeq} still holds exactly. We also ran a randomized search over the",
  "\\eqref{eq:blendeq} still holds exactly. A randomized search over the"),
 ("weight simplex and obtained the same optimum,",
  "weight simplex yields the same optimum,"),
 ("We split the labelled data once into an 80\\% development set (19{,}497",
  "The labelled data are split once into an 80\\% development set (19{,}497"),
 ("development set we use 5-fold cross-validation for both model selection and",
  "development set, 5-fold cross-validation is used for both model selection and"),
 ("tuning. We optimise MSE directly because that is the competition",
  "tuning. MSE is optimised directly because it is the evaluation"),
 ("metric, but we also track MAE and $R^2$ internally because they are easier to",
  "metric, while MAE and $R^2$ are also tracked internally because they are easier to"),
 ("read. To stop leakage, we (i) fit every preprocessing step only on",
  "read. To prevent leakage, (i) every preprocessing step is fitted only on"),
 ("the training fold, (ii) build no feature from Q3 2016 information, and (iii)",
  "the training fold, (ii) no feature is built from Q3 2016 information, and (iii)"),
 ("compute target encodings inside their own inner $K$-fold per",
  "target encodings are computed inside their own inner $K$-fold per"),
 ("\\eqref{eq:kfoldte}. As a last step we clip predictions to $[0,92]$ and round",
  "\\eqref{eq:kfoldte}. As a last step, predictions are clipped to $[0,92]$ and rounded"),
 ("Because the project had to run on a single workstation rather than a cluster, we\nkept an eye on cost throughout.",
  "Because the experiments ran on a single workstation rather than a cluster,\ncomputational cost was monitored throughout."),
 ("on average and takes about 10.6 seconds per 5-fold evaluation on our hardware, so",
  "on average and takes about 10.6 seconds per 5-fold evaluation on the hardware of Appendix~A, so"),
 ("This favourable cost profile is one practical reason we preferred a small,",
  "This favourable cost profile is one practical reason a small,"),
 ("well-tuned ensemble over a single very large model:",
  "well-tuned ensemble is preferred over a single very large model:"),
 ("and it is exactly the structural mismatch we made precise in",
  "and it is exactly the structural mismatch made precise in"),
 ("Section~\\ref{sec:linearcritique}: the relationship between our features and the",
  "Section~\\ref{sec:linearcritique}: the relationship between the features and the"),
 ("and our compute budget did not allow a deep search.",
  "and the compute budget did not allow a deep search."),
 ("when its internal validation error stopped improving gave us most of the benefit",
  "when its internal validation error stopped improving captured most of the benefit"),
 ("because the weak models drag it down. Once we let\nSLSQP choose the weights, the error dropped to 180.5",
  "because the weak models drag it down. Once\nSLSQP chooses the weights, the error drops to 180.5"),
 ("A drop from 182.2 to 180.5 MSE is small, so we tested whether it is real or just",
  "A drop from 182.2 to 180.5 MSE is small, so it is tested whether the gain is real or just"),
 ("19{,}497 development rows, we use a \\emph{paired} test on the per-sample squared\nerrors, the sample-level analogue",
  "19{,}497 development rows, a \\emph{paired} test on the per-sample squared\nerrors is used, the sample-level analogue"),
 ("signed-rank test agrees overwhelmingly ($p<10^{-50}$). We therefore reject $H_0$:",
  "signed-rank test agrees overwhelmingly ($p<10^{-50}$). $H_0$ is therefore rejected:"),
 ("hypothesis on our existing held-out predictions and is what our compute budget",
  "hypothesis on the existing held-out predictions and is what the compute budget"),
 ("systematic behaviour at the edges, so we examined the residuals",
  "systematic behaviour at the edges, so the residuals are examined"),
 ("To localize the bias we binned the rows by their true value and plotted the mean\nsigned residual per bin (Fig.~\\ref{fig:residualbins}).",
  "To localize the bias, the rows are binned by their true value and the mean\nsigned residual per bin (Fig.~\\ref{fig:residualbins}) is plotted."),
 ("model we propose in Section~\\ref{sec:concl}: a dedicated classifier for ``will",
  "model proposed in Section~\\ref{sec:concl}: a dedicated classifier for ``will"),
]

miss = []
for a, b in R:
    if a in s:
        s = s.replace(a, b)
    else:
        miss.append(a[:55])

io.open(F, 'w', encoding='utf-8').write(s)
import re
print('applied:', len(R) - len(miss), '/ remaining we:', len(re.findall(r'\\bwe\\b', s, re.I)),
      'our:', len(re.findall(r'\\bour\\b', s, re.I)), 'us:', len(re.findall(r'\\bus\\b', s)))
print('MISSES:')
for m in miss:
    print('  -', m)
